services:
  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    plan: free
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://backend-xxxx.onrender.com 